from app.schemas.autor_schemas import AutorSchemaCreate, AutorSchemaResponse, AutorSchemaUpdate
from app.schemas.libro_schemas import LibroCreateSchema, LibroResponseSchema, LibroUpdateSchema
from app.schemas.marcador_schemas import MarcadorSchemaCreate, MarcadorSchemaResponse, MarcadorSchemaUpdate
from app.schemas.progreso_schemas import ProgresoSchemaCreate, ProgresoSchemaResponse, ProgresoSchemaUpdate
from app.schemas.serie_schemas import SerieSchemaCreate, SerieSchemaResponse, SerieSchemaUpdate
from app.schemas.usuario_schemas import UsuarioSchemaCreate, UsuarioSchemaResponse, UsuarioSchemaUpdate, UsuarioSchemaLogin