from app.infrastructure.database.repositories.sqlalchemy_autor_repository import SQLAlchemyAutorRepository
from app.infrastructure.database.repositories.sqlalchemy_libro_repository import SQLAlchemyLibroRepository
from app.infrastructure.database.repositories.sqlalchemy_marcador_repository import SQLAlchemyMarcadorRepository
from app.infrastructure.database.repositories.sqlalchemy_progreso_repository import SQLAlchemyProgresoRepository
from app.infrastructure.database.repositories.sqlalchemy_serie_repository import SQLAlchemySerieRepository
from app.infrastructure.database.repositories.sqlalchemy_usuario_repository import SQLAlchemyUsuarioRepository